helm:
  parameters:
  - name: image.repository
    value: ghcr.io/mvs5465-test/cluster-query-router
    forcestring: true
  - name: image.tag
    value: main@sha256:03d5037747cc999036c54d675a7284515f443b46ceda4269854b87709cbced01
    forcestring: true
