helm:
  parameters:
  - name: image.repository
    value: ghcr.io/mvs5465-test/cluster-query-router
    forcestring: true
  - name: image.tag
    value: main@sha256:919925dbf160cbf06473fd699cdb5988fd8f6eff70e5d65b37b613356528e0e0
    forcestring: true
