helm:
  parameters:
  - name: image.repository
    value: ghcr.io/mvs5465-test/cluster-query-router
    forcestring: true
  - name: image.tag
    value: main@sha256:5cf33a0c41cdaeb385dfa2094e17aea305c26640888c1598c37467f2237ff183
    forcestring: true
